action_inherited();
scr_dialog("dude","aw nuts lady,            #im freaking out right now!")
scr_dialog("dude","im really going to go#on stage and sing infront#of a bunch of strangers...")
scr_dialog("dude","just thinking about#it is making my head spin!")
scr_dialog("dude","do you think I look alright?")
scr_dialog("lady","u")
scr_dialog("dude","sweet!             #i don't think i can compare#to you though! your makeup#looks great!")
scr_dialog("peeb","really funny joke, because like.         #her face looks exactly the#same because of the art style")
scr_dialog("cyan","HEY TROLLS!!!")
scr_dialog("lady","p")
scr_dialog("dude","C-CYAN???")
scr_dialog("cyan","I gotta say it was pretty rad#that you got these#vip tickets!")
scr_dialog("dude","oh well uh,    #I couldn't have done it#without...")
scr_dialog("dude","cd boy?                    #where is he?")
scr_dialog("cyan","UGH, he WAS going with#me but uh...")
scr_dialog("cyan","he didn't make it#past the metal detectors...")
scr_dialog("peeb","funny scene of cd boy sitting#outside on a bench")
scr_dialog("cyan","I can't believe I'm going#to meet gunk!!! I relate to her#so much!!!")
scr_dialog("dude","I dunno when I talked to#her she seemed kinda like a jerk.")
scr_dialog("cyan","--I relate to her so much!!!")
scr_dialog("lady","i")
scr_dialog("gunk","✓㋡Helllllo everybody!✓W#I hope you all didn't have too#much trouble making your way#here!")
scr_dialog("cyan","✓♠GUUNK!!! OMG I LOVE YOU!!!#HSDFHJFKLASJDFHJSKDHF✓W")
scr_dialog("lady","q")
scr_dialog("cyan","I'M A HUGE FAN!!!      #I'VE BEEN LISTENING TO YOUR MUSIC#SINCE I WAS 9!!!")
scr_dialog("cyan","I EVEN NAMED MY ROOMBA AFTER ONE#OF YOUR SONGS!")
scr_dialog("cyan","HE SHOULD BE MAKING HIS WAY IN#RIGHT NOW!!                                  #HE DOESN'T HAVE A TICKET BUT#HE SHOULD BE FINE")
scr_dialog("peeb","lol")
scr_dialog("gunk","wow thats uh.          #cool.")
scr_dialog("cyan","SHE THINKS IM COOL!!!")
scr_dialog("gunk","stop shaking me!")
scr_dialog("cyan","OMG so sorry!!!")
scr_dialog("dude","im sure its fine!")
scr_dialog("cyan","SHUT UP THAT WASN'T FOR YOU!")
scr_dialog("gunk","Well the shows just#about to start! are you all#excited!")
scr_dialog("cyan","YES!!!!")
scr_dialog("gunk","alright so we should stand on#this platform and when the show#starts, its going to rise up and#we'll be on stage!")
scr_dialog("dude","hoorraaaaaaay")
scr_dialog("lady","o")
scr_dialog("dude","huh?               #whats the karaoke machine#doing here?")
scr_dialog("cyan","LOL yeah! its that dumb music#box from the bus!")
scr_dialog("gunk","Thats not part of the set?!")
scr_dialog("tv","HELLO")
scr_dialog("dude","hi")
scr_dialog("gunk","%$!& Quick!         #you, blue girl!                #get that out of here!")
scr_dialog("cyan","Anything for you Gunk!")
scr_dialog("peeb","The platform starts moving up")
scr_dialog("gunk","C-crap! wait nevermind!")
scr_dialog("gunk","Just uh...")
scr_dialog("peeb","lady sits on top of the KAROKATE#machine")
scr_dialog("gunk","Yeah! perfect!        #they'll think its intentional!")
scr_dialog("cyan","I can sit on the karaoke#machine too!!!              #see gunk!!")
scr_dialog("gunk","yeah...              #thats cool...                  #I guess.")
scr_dialog("cyan","she thinks im cooler!!! >:)")
scr_dialog("lady","r")
scr_dialog("peeb","...")
scr_dialog("gunk","✓㋡HELLO EVERYBODY!!!")
scr_dialog("crowd","YAAAAAAAAAAAAAA!")
scr_dialog("gunk","This is going to be a very#special show everyone!")
scr_dialog("gunk","Tonight I'm accompanied by#the lovely...")
scr_dialog("gunk","...             #Whats your guys names?...")
scr_dialog("cyan","Cyan!")
scr_dialog("dude","you can call me dude!")
scr_dialog("lady","T")
scr_dialog("gunk","I'm accompanied by Jude, Ryan#and uh...                     #lady?")
scr_dialog("dude","what?")
scr_dialog("lady","u")
scr_dialog("gunk","To start off this show we'll#be singing--")
scr_dialog("cyan","GIRL NEXT DOOR!!!!!")
scr_dialog("gunk","Ew no way!           #I wrote that song when#I was like 12!")
scr_dialog("gunk","What song do you think we should#sing Jude?")
scr_dialog("dude","(crap, I don't know a thing#about this girls music)")
scr_dialog("dude","(im gonna look so dumb if I#tell her that!!)#")
scr_dialog("dude","(uh... lady?????)")
scr_dialog("lady","R")
scr_dialog("lady","Y")
scr_dialog("dude","daw cmon lady I cant#do charades right now!")
scr_dialog("lady","e")
scr_dialog("dude","alright ✓㋡fiiiine!")
scr_dialog("dude","computer...")
scr_dialog("lady","U")
scr_dialog("dude","redo...")
scr_dialog("lady","y")
scr_dialog("dude","crap, uh...          #around?")
scr_dialog("lady","u")
scr_dialog("lady","I")
scr_dialog("dude","earth...                  #oh I got it!")
scr_dialog("dude","evil space computers#invade the world!")
scr_dialog("lady","j")
scr_dialog("gunk","...                   #do you mean satellite.")
scr_dialog("dude","oh yeah sure-yeah!")
scr_dialog("peeb","boom")
scr_dialog("dude","WHAT WAS THAT")
scr_dialog("gunk","ahaha, those are the#fireworks!")
scr_dialog("gunk","Isn't that right?")
scr_dialog("peeb","boom")
scr_dialog("gunk","ahaha!")

///variables
shaking=false
splode=0
pause=true
gunkstare=0
roombaframe=-1
roombadone=false
alarm[0]=170 //outside scene
audio_play_sound(snd_crowd,9999,false) //placeholder crowd noise

